name: Update README by Books 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.2
    - run: npm install
      env:
        CI: true

    - name: Update README
      run: |-
        node update.js
        cat README.md
        
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "vvvv980@gmail.com"
        git config --global user.name "HongEunbeen"
        git add -A
        git commit -m "Updated README ( cheking books...)" || exit 0
        git push
